language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install:
    - pip install -r requirements.txt
    - mkdir packages
    - cd packages 
    - git clone https://github.com/mengzhuo/sqlalchemy-fulltext-search.git sqlfts 
    - cd sqlfts
    - python setup.py install
    - cd ../..
    - python routes.py &

script: 
    - python test.py